$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  samples:
    type: string
    default: config/samples.tsv
    description: Sample file
  data_dir:
    type: string
    default: data
    description: Where to download/read raw data from
  results_dir:
    type: string
    default: results
    description: Main folder for workflow output
  test:
    type: boolean
    default: false
    description: Whether to only dump a subset of reads from SRA
  threads:
    type: integer
    defalt: 8
    description: Max threads to use for workflow
    minimum: 1
  cutadapt:
    type: object
    default:
      FWD: "CTTGGTCATTTAGAGGAAGTAA"
      REV: "GCTGCGTTCTTCATCGATGC"
      n: 2
      minimum_length: 50
    properties:
      FWD:
        type: string
        description: Forward primer to cut
      REV:
        type: string
        description: Reverse primer to cut
      n:
        type: integer
      minimum_length:
        type: integer
        description: Minimum length for cutadapt
  dada2:
    type: object
    default:
      maxN: 0
      maxEE_R1: 6
      maxEE_R2: 6
      truncLen: 0
      truncQ: 2
      minLen: 50
    properties:
      maxN:
        type: integer
      maxEE_R1:
        type: integer
      maxEE_R1:
        type: integer
      truncLen:
        type: integer
      truncQ:
        type: integer
      minLen:
        type: integer

mock:
  type: array
  description: "Sample names to treat as 'mock' which will be separated prior to ASV clustering"
  default: []

# entries that have to be in the config file for successful validation
required:
  - samples